### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by cookacola** [Ouckah/Summer2025-Internships#1075]
### Link to Internship Posting

https://www.linkedin.com/jobs/view/system-verification-intern-at-shure-incorporated-4015122474

### Company Name

Shure

### Internship Title

System Verification Intern

### Location

Niles, Illinois

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

charchencw@gmail.com

**Comment by NPgreatest** [comment]
do not sponsor
