### ISSUE TITLE
Issue: Matroid Engineer Intern Requires US Citizenship

### ISSUE THREAD

**Issue by iamwyh2019** [Ouckah/Summer2025-Internships#1084]
### Select a category

Other

### Issue/Question/Closed Internship

For Matroid's Full Stack Engineer Intern, it seems that it requires US citizenship.

<img width="871" alt="image" src="https://github.com/user-attachments/assets/9583f03f-a837-4700-bc14-43806887c42d">

**Comment by vanshb03** [comment]
Hey @iamwyh2019 ,

Updated on recent push.
