### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by yawowususnr** [Ouckah/Summer2025-Internships#139]
### Link to Internship Posting

https://www.google.com/about/careers/applications/jobs/results/86639017272976070-software-engineering-intern-bs-summer-2025

### Company Name

Google

### Internship Title

Software Engineering Intern

### Location

Mountain View, CA, USA | Atlanta, GA, USA | +27 more

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

yawsnr@vt.edu

**Comment by Ouckah** [comment]
Thank you!
