### ISSUE TITLE
Issue: Rippling link broken or internship closed

### ISSUE THREAD

**Issue by UmarRS** [Ouckah/Summer2025-Internships#1568]
### Select a category

Closed Internship

### Issue/Question/Closed Internship

Rippling | Software Engineer Intern | San Francisco, CANew York, NY |   | Sep 24

This listing is broken or has been taken down.

**Comment by vanshb03** [comment]
Hey,

Just confirmed with Rippling and checked the link, role is still up.

Thank you for your contribution.
