### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by ndg24** [Ouckah/Summer2025-Internships#159]
### Link to Internship Posting

https://www.bmwgroup.jobs/us/en/jobfinder/job-description-copy.240000JR.html

### Company Name

BMW of North America

### Internship Title

Augmented Reality Engineer Intern

### Location

Mountain View, CA

### What season is this internship for?

Fall

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

nilansh.d.ghosh@vanderbilt.edu

**Comment by vanshb03** [comment]
LGTM! Thank you for your contribution 👍🏽
