### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by ndg24** [Ouckah/Summer2025-Internships#160]
### Link to Internship Posting

https://jobs.sap.com/job/San-Ramon-SAP-iXp-CXII-Intern-SoftwareML-Engineer-CA-94583/1081937001

### Company Name

SAP

### Internship Title

Software/ML Engineer Intern

### Location

San Ramon, CA

### What season is this internship for?

Fall

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

nilansh@outlook.com

**Comment by vanshb03** [comment]
LGTM! Thank you for your contribution 👍🏽
