### ISSUE TITLE
Google Software Engineering Intern for MS in Summer 2025

### ISSUE THREAD

**Issue by Linchen-Xu** [Ouckah/Summer2025-Internships#161]
### Link to Internship Posting

https://www.google.com/about/careers/applications/jobs/results/128518435922420422-software-engineering-intern-ms-summer-2025

### Company Name

Google

### Internship Title

Software Engineering Intern, MS, Summer 2025

### Location

Mountain View, CA | Atlanta, GA | Austin, TX | Boulder, CO | Cambridge, MA | Chicago, IL | Irvine, CA | Kirkland, WA | Los Angeles, CA | Madison, WI | New York, NY | Palo Alto, CA | Portland, OR | Pittsburgh, PA | Ryleigh, NC | Durham, NC | Reston, VA | Redmond, WA | Redwood City, CA | San Diego, CA | Goleta, CA | San Bruno, CA | Seattle, WA | San Francisco, CA | San Jose, CA | Santa Cruz, CA | Sunnyvale, CA | Washington, DC

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

592789211@qq.com

### Extra Notes (Optional)

Opens until June 21st, 2024.

**Comment by vanshb03** [comment]
Thank you for this @Linchen-Xu, will make the formatting change on Location to match the repo :)

**Comment by vanshb03** [comment]
Just made the update, thank you for your contribution :)
