### ISSUE TITLE
Google Software Engineering Intern for MS in Summer 2025

### ISSUE THREAD

**Issue by jiejun-j** [Ouckah/Summer2025-Internships#164]
### Link to Internship Posting

https://www.google.com/about/careers/applications/jobs/results/128518435922420422-software-engineering-intern-ms-summer-2025?target_level=INTERN_AND_APPRENTICE

### Company Name

Google

### Internship Title

Software Engineering Intern, MS, Summer 2025

### Location

Mountain View, CA, USA ; Atlanta, GA, USA ; +26 more

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

jiang.jiej@northeastern.edu

### Extra Notes (Optional)

Google provides separate application portals for Bachelor's and Master's degrees. This is the application link specifically for the Master's degree.

**Comment by vanshb03** [comment]
Hey Jiejun, we just added the Masters internship onto the repo from an earlier git-issue. Thank you so much for your contribution :)
