### ISSUE TITLE
New Internship - Fundamental Research Analyst Intern at The D. E. Shaw Group

### ISSUE THREAD

**Issue by sample-resume** [Ouckah/Summer2025-Internships#18]
### Link to Internship Posting

https://www.deshaw.com/careers/fundamental-research-analyst-intern-new-york-summer-2025-4988

### Company Name

The D. E. Shaw Group

### Internship Title

Fundamental Research Analyst Intern – Summer 2025

### Location

New York

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

andrew@sampleresu.me

### Extra Notes (Optional)

Not positive about internship sponsorship, but in their FAQs about sponsorship, it says they do. https://www.deshaw.com/careers/faq

**Comment by Ouckah** [comment]
This seems to be more financial than technical, I'll see what the CS heads think about having financial internships on here, thank you for the submission!

**Comment by sample-resume** [comment]
No problem! I didn't realize the list was for technical internships - will add any technical internships that I come across :)

**Comment by Ouckah** [comment]
Thank you! Closing this issue now.
