### ISSUE TITLE
Palantir

### ISSUE THREAD

**Issue by nishkp** [Ouckah/Summer2025-Internships#189]
### Link to Internship Posting

https://jobs.lever.co/palantir/0adba6bd-d4b0-4fc2-9014-315f0f0b72b9

### Company Name

Palantir

### Internship Title

Various (Semester at Palantir, Internship)

### Location

New York, NY, US

### What season is this internship for?

Fall

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

nishkdpatel@gmail.com

**Comment by vanshb03** [comment]
LGTM! Thank you for the contribution 👍🏽
