### ISSUE TITLE
New Internship - Software Engineer Internship at Chicago Trading Company, LLC Referral

### ISSUE THREAD

**Issue by sample-resume** [Ouckah/Summer2025-Internships#19]
### Link to Internship Posting

https://boards.greenhouse.io/chicagotradingreferral/jobs/4392240005

### Company Name

Chicago Trading Company

### Internship Title

Software Engineer Internship - Summer 2025

### Location

Chicago, IL

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

andrew@sampleresu.me

### Extra Notes (Optional)

**Application Timeline** 
Please apply by October 1st, 2024. 

- Following the application process, you may receive an online assessment from Codility to test your programming skills.
- Based on your assessment results, you may be invited to a virtual interview. We will notify you about your interview status on a rolling basis where possible and no later than early October 2023 (typo in the posting).

**Comment by Ouckah** [comment]
Hi Andrew! Unfortunately, we have already added this position opening in a [previous issue](https://github.com/Ouckah/Summer2025-Internships/issues/12). Thank you for the contribution! Closing this issue.

**Comment by sample-resume** [comment]
I added the wrong one from CTC 🤦

**Comment by Ouckah** [comment]
Haha, no problem!
