### ISSUE TITLE
Internship / Finale thesis- Test automation for software tools

### ISSUE THREAD

**Issue by Mohamed-khaled0** [Ouckah/Summer2025-Internships#1919]
### Link to Internship Posting

https://career.iav.com/en/careers/jobs/working-student-internship-finale-thesis-test-automation-for-software-tools/

### Company Name

IAV GmbH

### Internship Title

Internship-  Test automation for software tools

### Location

Gifhorn

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by vanshb03** [comment]
Hey,

The repo currently only supports roles in NA. Thank you for your contribution.
