### ISSUE TITLE
Intern/Working Student – Test Engineer 

### ISSUE THREAD

**Issue by Mohamed-khaled0** [Ouckah/Summer2025-Internships#1920]
### Link to Internship Posting

https://mbition.io/career/internship-test-engineer-all-genders/

### Company Name

 MBition GmbH

### Internship Title

Test Engineer Intern

### Location

Berlin

### What season is this internship for?

Fall

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by vanshb03** [comment]
Hey,

The repo currently only supports roles in NA. Thank you for your contribution.
