### ISSUE TITLE
Apple Machine Learning Internship

### ISSUE THREAD

**Issue by agyemangy18** [Ouckah/Summer2025-Internships#199]
### Link to Internship Posting

https://jobs.apple.com/en-us/details/200554363/machine-learning-ai-internships

### Company Name

Apple

### Internship Title

Machine Learning Internship 2025

### Location

United States

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

agyemangy18@vt.edu

**Comment by vanshb03** [comment]
Hey @agyemangy18, the role was added earlier today onto the repo. Thank you so much for the contribution :)
