### ISSUE TITLE
Rippling

### ISSUE THREAD

**Issue by nishkp** [Ouckah/Summer2025-Internships#209]
### Link to Internship Posting

https://ats.rippling.com/rippling/jobs/c164fa22-6164-4bc0-8d53-89d856c4065a

### Company Name

Rippling

### Internship Title

Front End Software Engineer Intern

### Location

New York, NY, US | San Francisco, CA

### What season is this internship for?

Spring

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

nishkdpatel@gmail.com

**Comment by vanshb03** [comment]
LGTM, thank you for the contribution 👍🏽
