### ISSUE TITLE
2025 Capstone Investment Advisors Summer Internship - Software Engineering

### ISSUE THREAD

**Issue by LuaanNguyen** [Ouckah/Summer2025-Internships#211]
### Link to Internship Posting

https://boards.greenhouse.io/capstoneinvestmentadvisors/jobs/7470795002?gh_src=d1e300ab2us

### Company Name

Capstone Investment Advisors

### Internship Title

Software Engineer Intern

### Location

 New York, NY | Hybrid

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by vanshb03** [comment]
Hey @LuaanNguyen ,

Thank you for the contribution :)

Closing the issue as the job exists on ```listings.json```
