### ISSUE TITLE
Blue Origin 2025 Spring Internship

### ISSUE THREAD

**Issue by LuaanNguyen** [Ouckah/Summer2025-Internships#212]
### Link to Internship Posting

https://blueorigin.wd5.myworkdayjobs.com/BlueOrigin/job/Seattle-WA/Spring-2025-Software-Engineering-Intern---Undergraduate_R44510

### Company Name

Blue Origin

### Internship Title

Software Engineering Intern

### Location

Seattle, WA | Space Coast, FL

### What season is this internship for?

Spring

### Does this internship offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by vanshb03** [comment]
Hey @LuaanNguyen ,

Thank you for the contribution :)

Closing the issue as the job exists on listings.json
