### ISSUE TITLE
New Internship (Investment Engineer Intern - Summer 2025 at Bridgewater Associates Campus Recruiting)

### ISSUE THREAD

**Issue by sample-resume** [Ouckah/Summer2025-Internships#24]
### Link to Internship Posting

https://boards.greenhouse.io/bridgewatercampusrecruiting/jobs/7239499002

### Company Name

Bridgewater Associates

### Internship Title

Investment Engineer Intern

### Location

Westport, CT

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

andrew@sampleresu.me

**Comment by Ouckah** [comment]
Completely forgot this one! Good catch!
