### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by KingFriizy** [Ouckah/Summer2025-Internships#271]
### Link to Internship Posting

https://morganstanley.tal.net/vx/lang-en-GB/mobile-0/brand-2/xf-53fdfbaf0394/candidate/so/pm/1/pl/1/opp/17297-2025-Technology-Summer-Analyst-Program-New-York/en-GB

### Company Name

Morgan Stanley

### Internship Title

2025 Technology Summer Analyst Program (New York)

### Location

New York, NY | Boston, MA | Alpharetta, GA 

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

zwright5270@gmail.com

### Extra Notes (Optional)

did not find anything on sponsorship

**Comment by vanshb03** [comment]
Thank you for your contribution :)
