### ISSUE TITLE
Internship posting update

### ISSUE THREAD

**Issue by rahil0707** [Ouckah/Summer2025-Internships#275]
### Link to Internship Posting

https://careers-iridium.icims.com/jobs/3698/intern%2C-software-engineering/job

### Company Name

Iridium

### Internship Title

Software Engineering Intern

### Location

Folsom, CA

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

rahilhussain10@gmail.com

**Comment by vanshb03** [comment]
Thank you for your contribution @rahil0707, resolved in #286
