### ISSUE TITLE
New Internship - SIG

### ISSUE THREAD

**Issue by LuaanNguyen** [Ouckah/Summer2025-Internships#308]
### Link to Internship Posting

https://careers.sig.com/job/8218/Software-Engineering-Internship-Summer-2025

### Company Name

SIG

### Internship Title

Software Engineering intern

### Location

Philadelphia, PA (Onsite)

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

luanthiennguyen2003@gmail.com

**Comment by vanshb03** [comment]
Hey @LuaanNguyen ,

Thank you for the contribution :)

Closing the issue as the job exists on ```listings.json```
