### ISSUE TITLE
palantir SWEI NY

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#317]
### Link to Internship Posting

https://jobs.lever.co/palantir/7d69cf8a-06fd-4f05-bd84-27149db29c4d

### Company Name

Palantir

### Internship Title

Software Engineer Intern

### Location

New York, NY

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by csjh** [comment]
If it needs security clearance then I don’t think it could offer sponsorship

**Comment by beakae** [comment]
> If it needs security clearance then I don’t think it could offer sponsorship

good catch. let me change them all

**Comment by vanshb03** [comment]
LGTM! Thanks for your contribution!
