### ISSUE TITLE
palantir SWEI D.C

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#318]
### Link to Internship Posting

https://jobs.lever.co/palantir/bdcfb29f-4f27-42de-933f-7f83a359b9f0?Wash-DC

### Company Name

Palantir

### Internship Title

Software Engineer Intern

### Location

Washington, DC

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by vanshb03** [comment]
Rookie mistake on my end :)

LGTM! Thanks for your contribution!
