### ISSUE TITLE
palantir SWEI palo alto

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#320]
### Link to Internship Posting

https://jobs.lever.co/palantir/e27af7ab-41fc-40c9-b31d-02c6cb1c505c

### Company Name

Palantir

### Internship Title

Software Engineer Intern

### Location

Palo Alto, CA

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by vanshb03** [comment]
LGTM! Thanks for your contribution!
