### ISSUE TITLE
Issue: Application links with redirecting do not load

### ISSUE THREAD

**Issue by cmckenney1127** [Ouckah/Summer2025-Internships#3202]
### Select a category

Other

### Issue/Question/Closed Internship

I click on the links and half of the time it doesn't load or says the connection has been blocked.
![image](https://github.com/user-attachments/assets/b5c75ec9-d7ae-4130-bf39-a9e1199a2759)

**Comment by Niggling** [comment]
![image](https://github.com/user-attachments/assets/c60c2013-49dd-4e4d-8aa4-85d68ac9e02d)
me too

**Comment by vanshb03** [comment]
Hey @cmckenney1127 ,

Just started a conversation with the ISP(Plume) and will share updates on the thread on the issue

**Comment by vanshb03** [comment]
> ![image](https://private-user-images.githubusercontent.com/97212966/396317599-c60c2013-49dd-4e4d-8aa4-85d68ac9e02d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzkwMTIsIm5iZiI6MTczNDQzODcxMiwicGF0aCI6Ii85NzIxMjk2Ni8zOTYzMTc1OTktYzYwYzIwMTMtNDlkZC00ZTRkLThhYTQtODVkNjhhYzllMDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEyMzE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhOWM1MTQ0YTI2YWRmNWY1OTc1OGI4MTkwMDE2NzBiNWZhYjQyOWFiZTU2NzA1NjI3YjYyNTYyYzg4M2Y1NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._qA49g6UkxfG_WeevcOCofZXBYoRWwpGmmIVmRzEUqY) me too

Hey @Niggling 

There was an issue on redirect on our end with the SSL and just resolved it. Let me know if it works now on your end!

**Comment by cmckenney1127** [comment]
Alright it works now. Thanks
