### ISSUE TITLE
Issue: Google Will Not Allow Me To Connect redirect.curve

### ISSUE THREAD

**Issue by willhuang2017** [Ouckah/Summer2025-Internships#3235]
### Select a category

Other

### Issue/Question/Closed Internship

redirect.cvrve.me normally uses encryption to protect your information. When Chrome tried to connect to redirect.cvrve.me this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be redirect.cvrve.me, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit redirect.cvrve.me right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by vanshb03** [comment]
Hey @willhuang2017 

There was an issue on redirect on our end with the SSL and just resolved it. Let me know if it works now on your end!
