### ISSUE TITLE
Issue: "Did Not Connect" popup cvrve links

### ISSUE THREAD

**Issue by zheintzleman** [Ouckah/Summer2025-Internships#3240]
### Select a category

Other

### Issue/Question/Closed Internship

![image](https://github.com/user-attachments/assets/61962469-21cf-4d32-9ab5-6a353f6451ea)
When I try to click the link to the recent little caesars swe internship ( https://redirect.cvrve.me/046c159661d7f9048958?utm_source=ouckah ), it gives the above popup saying the website likely has an invalid/expired certificate.

**Comment by vanshb03** [comment]
Hey @zheintzleman ,

There was an issue on redirect on our end with the SSL and just resolved it. Let me know if it works now on your end!

**Comment by zheintzleman** [comment]
Yep, it seems to work now!
