### ISSUE TITLE
JPMC DS

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#327]
### Link to Internship Posting

https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210531712

### Company Name

J. P. Morgan

### Internship Title

Data Science Intern

### Location

Chicago, IL | Planto, TX | Columbus, OH | New York, NY | Wilmington, DE

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by vanshb03** [comment]
LGTM! Thanks for your contribution!
