### ISSUE TITLE
JPMC Trading

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#329]
### Link to Internship Posting

https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210531228

### Company Name

J. P. Morgan

### Internship Title

Systematic Trading Analyst Intern

### Location

New York, NY

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by vanshb03** [comment]
LGTM! Thanks for your contribution!
