### ISSUE TITLE
Same Company Automation

### ISSUE THREAD

**Issue by Ouckah** [Ouckah/Summer2025-Internships#33]
Group listings with the same company in the same section of the list, image provided.

This change must also effect how we read from `.github/scripts/listings.json`!

![image](https://github.com/Ouckah/Summer2025-Internships/assets/43829909/2cb78e93-b065-4a35-9b3c-d66d50ed40b7)

**Comment by vanshb03** [comment]
Love the idea but curious on what will need to be amended to support this; 

For example: If a company releases **ROLE 1** on May 2nd but **Role 2** on May 5th, in the case we group them, we will either;
- Change the date of **Role 2** to be on an previous date and then do the grouping
- Change the date of **Role 1** to be sooner and then do the grouping
- Discard the sorting done based on dates currently

**Comment by Ouckah** [comment]
> Love the idea but curious on what will need to be amended to support this;
> 
> For example: If a company releases **ROLE 1** on May 2nd but **Role 2** on May 5th, in the case we group them, we will either;
> 
> * Change the date of **Role 2** to be on an previous date and then do the grouping
> * Change the date of **Role 1** to be sooner and then do the grouping
> * Discard the sorting done based on dates currently
> 
> Thoughts? @Ouckah @JhaoZ

I think the second option is optimal, just bump up the previous roles so the user doesn't have to scroll down to see the new roles.

**Comment by Ouckah** [comment]
Gonna make a branch and try to work this out.

**Comment by Ouckah** [comment]
That did not work.

**Comment by Ouckah** [comment]
Fixed, going to open a new issue for the NEW issue!
