### ISSUE TITLE
Palantir FDSWE (Gov) NY

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#331]
### Link to Internship Posting

https://jobs.lever.co/palantir/e0010393-c300-446f-bf67-fa2ef067f16f

### Company Name

Palantir

### Internship Title

Forward Deployed Software Engineer Intern

### Location

New York, NY

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by vanshb03** [comment]
LGTM! Thanks for your contribution!
