### ISSUE TITLE
Palantir FDSWE (Gov) DC

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#332]
### Link to Internship Posting

https://jobs.lever.co/palantir/e6ff8bf2-135e-474d-ad37-24f490ae1dd2

### Company Name

Palantir

### Internship Title

Forward Deployed Software Engineer Intern 

### Location

Washington, DC

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by vanshb03** [comment]
LGTM! Thanks for your contribution!
