### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by jhileman07** [Ouckah/Summer2025-Internships#337]
### Link to Internship Posting

https://optiver.com/working-at-optiver/career-opportunities/7498434002/

### Company Name

Optiver

### Internship Title

Software Engineering Intern

### Location

Austin, TX

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

johnhileman2026@u.northwestern.edu

**Comment by vanshb03** [comment]
LGTM! Thanks for your contribution!
