### ISSUE TITLE
Make offcycle

### ISSUE THREAD

**Issue by MrBulldog25** [Ouckah/Summer2025-Internships#34]
https://github.com/MrBulldog25/Summer2025-Internships/tree/off_cycle

I started it here

**Comment by vanshb03** [comment]
Looks solid, thoughts on prospectively adding a row for seasons, and if so, where do you see it best fit?

**Comment by MrBulldog25** [comment]
Maybe in the column before the application link?  We can have a dates thing

Also, may want to think about having several readmes, one for each season (depending on how active 2025 winter/spring is)

**Comment by vanshb03** [comment]
Sounds good, will dabble with it in a bit and happy to get your input in it as well, working on it the [feat#34](https://github.com/Ouckah/Summer2025-Internships/tree/feat%2334) branch :)
