### ISSUE TITLE
cit SWE

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#356]
### Link to Internship Posting

https://www.citadel.com/careers/details/software-engineer-2025-intern-us-2/

### Company Name

Citadel

### Internship Title

Software Engineer Intern

### Location

Chicago, IL | Miami, FL | New York, NY

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by vanshb03** [comment]
Amended :)

Thanks for your contribution 

#360

**Comment by vanshb03** [comment]
Just noticed this role is Cit mb :/
