### ISSUE TITLE
tt swe privacy seattle

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#376]
### Link to Internship Posting

https://careers.tiktok.com/position/7266223645327395127/detail

### Company Name

Tiktok

### Internship Title

Software Engineer Intern, Privacy and Security

### Location

Seattle, WA

### What season is this internship for?

Fall

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by beakae** [comment]
change title of old posting

**Comment by vanshb03** [comment]
I broke the bot :(
