### ISSUE TITLE
Comcast swe co-op | fall

### ISSUE THREAD

**Issue by ibrakhimus** [Ouckah/Summer2025-Internships#386]
### Link to Internship Posting

https://comcast.wd5.myworkdayjobs.com/Comcast_Careers/job/PA---Philadelphia-1701-John-F-Kennedy-Blvd/Comcast-Software-Engineer-Co-op_R390940

### Company Name

Comcast

### Internship Title

Comcast Software Engineer Co-op

### Location

Philadelphia, PA

### What season is this internship for?

Fall

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ibrakhimus@gmail.com

**Comment by beakae** [comment]
@vansh put that this is a HQ position. theres another comcast swe coop in PA
