### ISSUE TITLE
Ventas, Inc are unable to sponsor or assume sponsorship of an employment Visa at this time

### ISSUE THREAD

**Issue by chihyuchang21** [Ouckah/Summer2025-Internships#403]
### Link to Internship Posting

none

### Company Name

Ventas, Inc

### Internship Title

Software Engineer Intern

### Location

Chicago, IL	

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

chihyuchang21@gmail.com

### Extra Notes (Optional)

Updated that Ventas are unable to sponsor or assume sponsorship of an employment Visa at this time

**Comment by vanshb03** [comment]
Thank you for your contribution; amended with #425
