### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by chenyuan99** [Ouckah/Summer2025-Internships#43]
### Link to Internship Posting

https://search.jobs.barclays/job/new-york/transaction-banking-analyst-internship-program-2025-new-york/13015/62566446208?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic

### Company Name

Barclays

### Internship Title

Transaction Banking Analyst Internship Program 2025 New York

### Location

New York, NY

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

cysbc1999@gmail.com

**Comment by Ouckah** [comment]
Hi @chenyuan99! Thank you for the submission, however, we're trying to keep this repo strictly for software engineering / technical internships.
