### ISSUE TITLE
New Internship for SIG

### ISSUE THREAD

**Issue by raoanmol** [Ouckah/Summer2025-Internships#44]
### Link to Internship Posting

https://careers.sig.com/job/8253/Quantitative-Research-Intern-Summer-2025

### Company Name

SIG

### Internship Title

Quantitative Research Intern

### Location

Bala Cynwyd, PA

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

raoanmol@outlook.com

### Extra Notes (Optional)

Only for PhD students

**Comment by Ouckah** [comment]
I heard the PhD requirement was bendy, my friend knows an undergrad who had the internship because they had cracked experience, so I'll add this!
