### ISSUE TITLE
PDT Partners Summer 2025 SWE Internship

### ISSUE THREAD

**Issue by peterli135** [Ouckah/Summer2025-Internships#451]
### Link to Internship Posting

https://boards.greenhouse.io/pdtpartners/jobs/4423823

### Company Name

PDT Partners

### Internship Title

Software Engineering Intern

### Location

New York, NY

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

**Comment by vanshb03** [comment]
Thank you for your contribution :)
