### ISSUE TITLE
Comcast ERP Internship - Technology

### ISSUE THREAD

**Issue by kameron-h** [Ouckah/Summer2025-Internships#497]
### Link to Internship Posting

https://comcast.wd5.myworkdayjobs.com/en-US/Comcast_Careers/job/ERP-Internship--Rising-Senior-Technology_R391520

### Company Name

Comcast

### Internship Title

Enterprise Rotational Program Internship: Rising Senior Technology

### Location

Philadelphia, PA | Orlando, FL | Sunnyvale, CA | New York, NY | Englewood, CO

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kmrnharrison@gmail.com

**Comment by vanshb03** [comment]
Just had a look at Comcast's workday, they closed this role already.

Thank you for your contribution.
