### ISSUE TITLE
Software Application Engineering Intern (Summer 2025)

### ISSUE THREAD

**Issue by Dragons-Lai** [Ouckah/Summer2025-Internships#501]
### Link to Internship Posting

https://www.linkedin.com/jobs/view/3973375440/?alternateChannel=search&refId=NotAvailable

### Company Name

Axiom Space

### Internship Title

Software Application Engineering Intern (Summer 2025)

### Location

Houston, TX

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

dragons870409@gmail.com

**Comment by vanshb03** [comment]
Just took at the role from the Bamboo, shows that the role is closed.

Thank you for your contribution

**Comment by Dragons-Lai** [comment]
https://axiomspace.bamboohr.com/careers/939

Is that so? It seems like it can still be applied😂
