### ISSUE TITLE
feat: conferences/other events

### ISSUE THREAD

**Issue by vanshb03** [ouckah/Summer2025-Internships#51]
With MongoDB's Women in Computer Science Summit (AMER), MongoDB's Next in Tech Summit (AMER), Code for Good coming up, should we build that onto this repo under another markdown?

Thoughts @JhaoZ @Ouckah

**Comment by Ouckah** [comment]
I like that idea, adding something like events or summits.

**Comment by vanshb03** [comment]
Currently feeding into https://hack.cvrve.me

Will scale a better solution
