### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by shah527** [Ouckah/Summer2025-Internships#52]
### Link to Internship Posting

https://haier.wd3.myworkdayjobs.com/GE_Appliances/job/USA-Louisville-KY/Software-Engineering-Co-op-Spring-2025_REQ-18849

### Company Name

GE Appliances

### Internship Title

Software Engineering Co-op | Spring 25

### Location

Louisville, KY

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

shahmdmahir03@gmail.com

### Extra Notes (Optional)

co-op role

**Comment by Ouckah** [comment]
Please resubmit using the new `New Internship` issue template! Sorry for having you resubmit the same internship 😭.
