### ISSUE TITLE
Wells Fargo Summer 2025 Technology Internship

### ISSUE THREAD

**Issue by ethan-j-xu** [Ouckah/Summer2025-Internships#541]
### Link to Internship Posting

https://www.wellsfargojobs.com/en/jobs/r-385829/2025-technology-summer-internship-early-careers-software-or-data-engineer/?utm_source=Simplify&ref=Simplify

### Company Name

Wells Fargo

### Internship Title

2025 Technology Summer Internship - Early Careers (Software or Data Engineer)

### Location

Charlotte, NC | Addision, TX | Chandler, AZ | Irving, TX | Minneapolis, MN | Phoenix, AZ | Saint Louis, MO | Summit, NJ

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ethanjxu1@gmail.com

**Comment by csjh** [comment]
<img width="613" alt="image" src="https://github.com/user-attachments/assets/c6512243-8d51-4d3f-8027-68a3a863674f">
no sponsorship

**Comment by vanshb03** [comment]
Hey hey,

I had the role on the dev branch and hadn't merged it. It is now on the repo :)
