### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by adisinghstudent** [Ouckah/Summer2025-Internships#548]
### Link to Internship Posting

https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Software-Intern---Autonomous-Vehicles_JR1978798

### Company Name

Nvidia

### Internship Title

Software Intern

### Location

Shanghai | Shenzhen

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

adis@ntnu.no

### Extra Notes (Optional)

Exciting opportunity in China

**Comment by avishj** [comment]
This intern is not in NA / Remote, which is what this repo tracks.

**Comment by Vaibhav-Thalanki** [comment]
Is there an opening in USA/Remote?

**Comment by vanshb03** [comment]
Hey hey,

The role is outside the US and would not fit for the repo.

Thank you for the contribution :)
