### ISSUE TITLE
Issue: Broken Internship Link

### ISSUE THREAD

**Issue by Cole-Hartman** [Ouckah/Summer2025-Internships#562]
### Select a category

Other

### Issue/Question/Closed Internship

Company: Software
Role: Software Analyst Intern
Location: Oklahoma City, OK
Date: Jul 24
Link: http://paycom.terrico.io/?utm_source=404&utm_medium=301-redirect&utm_campaign=job-postings&utm_content=old

**Comment by vanshb03** [comment]
Hey @Cole-Hartman ,

Fixed link in the most recent merge, thank you for your contribution <3
