### ISSUE TITLE
Issue: Updated Notion Internship application locations 

### ISSUE THREAD

**Issue by alex-mcneilly** [Ouckah/Summer2025-Internships#581]
### Select a category

Suggestion

### Issue/Question/Closed Internship

Hi Notion's internship applications are not on Wellfound but on RippleMatch. This is the link to the new internship applications: https://app.ripplematch.com/v2/public/company/notion

**Comment by vanshb03** [comment]
Hey Alex,

Made the update/change on the link :)

Thank you so much for the contribution!
