### ISSUE TITLE
Issue: Prudential Internship Does Not Sponsor Visa

### ISSUE THREAD

**Issue by haozed** [Ouckah/Summer2025-Internships#618]
### Select a category

Other

### Issue/Question/Closed Internship

Written in the second bullet point of 'Required Qualifications' section: 
"Prudential does not provide visa sponsorship for this position. Successful candidates must possess the requisite US employment authorization to be eligible for consideration"
So a 🛂  icon is missing.

**Comment by vanshb03** [comment]
Hey @haozed ,

Made the change with 2650882 :)
