### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by haozed** [Ouckah/Summer2025-Internships#624]
### Link to Internship Posting

https://ventas.wd1.myworkdayjobs.com/VTR_NonPublic/job/IL---Chicago/Intern--Software-Engineering--Summer-2025-_R0001113-2

### Company Name

Ventas

### Internship Title

Software Engineering Intern

### Location

Chicago, IL

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

haoze04@gmail.com

**Comment by vanshb03** [comment]
Thank you for your contribution!
