### ISSUE TITLE
Issue: Pepsi link accessibility and sponsorship limitation

### ISSUE THREAD

**Issue by yogarajalakshmi-s** [Ouckah/Summer2025-Internships#640]
### Select a category

Other

### Issue/Question/Closed Internship

1. Provided link for Pepsi Co. Summer Internship isn't working. Accessible link: [https://www.pepsicojobs.com/main/jobs/315338?lang=en-us&previousLocale=en-US](https://www.pepsicojobs.com/main/jobs/315338?lang=en-us&previousLocale=en-US)

2. Written in the **Minimum Qualifications** section:
"Minimum Qualifications - Each candidate is expected to: 
This position is limited to persons with indefinite right to work in the United States."
So this 🛂 icon is missing.

**Comment by vanshb03** [comment]
Hey @yogarajalakshmi-s ,

Thank you for your contribution, made the updates :)
