### ISSUE TITLE
Terra API

### ISSUE THREAD

**Issue by anaiskillian** [Ouckah/Summer2025-Internships#648]
### Link to Internship Posting

https://www.ycombinator.com/companies/terra/jobs/QX8I6M5-software-engineer

### Company Name

Terra API

### Internship Title

Software Engineer

### Location

London, UK

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

anaiskillian@gmail.com

**Comment by vanshb03** [comment]
Hey @anaiskillian ,

This role is outside NA(Canada, US) and will not be able to feature it on this repo.

Thank you for your contribution!
