### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by yonatantussa** [Ouckah/Summer2025-Internships#66]
### Link to Internship Posting

https://www.capitalonecareers.com/job/mclean/labs-incubator-intern-2024-2025-academic-year/31238/64704828368

### Company Name

Capital One

### Internship Title

Labs Incubator Intern

### Location

Mclean, VA | Chicago, Illinois

### What season is this internship for?

Fall/Spring

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ytussa@montgomerycollege.edu

**Comment by JhaoZ** [comment]
This is mostly a academic year program for UIUC and UMD only, so while this is a good off season internship, I think it wouldn't fall under 2025 summer;
