### ISSUE TITLE
Issue: Capital One Sponsorship

### ISSUE THREAD

**Issue by alecishuman** [Ouckah/Summer2025-Internships#660]
### Select a category

Suggestion

### Issue/Question/Closed Internship

I tried applying to the new Capital One role, but it mentions it doesn't offer sponsorships. I think it would be good to label the Capital One as no sponsorship offers.

**Comment by vanshb03** [comment]
Hey @alecishuman ,

Just updated sponsorship state for all roles, thank you for your contribution!
