### ISSUE TITLE
Issue: BNY Mellon	Engineering Internship does not offer sponsorship

### ISSUE THREAD

**Issue by haoz1119** [Ouckah/Summer2025-Internships#687]
### Select a category

Suggestion

### Issue/Question/Closed Internship

On the website this internship linked to, it stated in the Program Eligibility: "Does not require sponsorship for employment visa status (now or in the future) in the country where applying", which indicates this internship does not offer sponsorship.

**Comment by vanshb03** [comment]
Hey @haozhou1919 ,

Updating in the next push. Thank you for your contribution!
