### ISSUE TITLE
Issue: Eaton Software Engineer Intern does not offer sponsorship

### ISSUE THREAD

**Issue by haoz1119** [Ouckah/Summer2025-Internships#688]
### Select a category

Suggestion

### Issue/Question/Closed Internship

On the website this internship linked to, it states that "require qualification: •    Must be legally authorized to work in the United States without company sponsorship now and in the future", which indicates that this internship does not offer sponsorship.

**Comment by vanshb03** [comment]
Hey @haozhou1919 ,

Updating in the next push. Thank you for your contribution!
