### ISSUE TITLE
Issue: Both Alpha FMC Internships Closed

### ISSUE THREAD

**Issue by PresidentSam100** [Ouckah/Summer2025-Internships#698]
### Select a category

Question

### Issue/Question/Closed Internship

https://boards.greenhouse.io/alphaawmnaearlycareers/jobs/7482799002
https://boards.greenhouse.io/alphaawmnaearlycareers/jobs/7482769002

**Comment by vanshb03** [comment]
Hey @PresidentSam100 ,

Closed roles.

Thanks for your contribution!
