### ISSUE TITLE
PayPal Software Engineer Intern Summer 2025

### ISSUE THREAD

**Issue by peterli135** [Ouckah/Summer2025-Internships#701]
### Link to Internship Posting

https://paypal.eightfold.ai/careers?query=R0115646&pid=274902335251&domain=paypal.com&sort_by=relevance

### Company Name

PayPal

### Internship Title

Software Engineer Intern

### Location

San Jose, CA | Chicago, IL | Omaha, NE | Scottsdale, AZ | New York City, NY | Austin, TX

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

peterli9713@outlook.com

**Comment by aidanouckama** [comment]
Thank you!
