### ISSUE TITLE
Issue: Delta internship has MSP office

### ISSUE THREAD

**Issue by amyipdev** [Ouckah/Summer2025-Internships#710]
### Select a category

Suggestion

### Issue/Question/Closed Internship

The Delta internships, while primarily targeting Atlanta, GA, also allow applicants during the interview to request placement in Delta's Minneapolis/St. Paul, MN office.
![image](https://github.com/user-attachments/assets/6f4618f9-fe4a-4e98-98c1-3a2646904308)
https://delta.avature.net/en_US/careers/JobDetail?jobId=25672

**Comment by vanshb03** [comment]
Hey @amyipdev ,

Making the update in the next commit!
