### ISSUE TITLE
Issue: Phillips requires candidates must be US citizen.

### ISSUE THREAD

**Issue by xiangddang** [Ouckah/Summer2025-Internships#712]
### Select a category

Suggestion

### Issue/Question/Closed Internship

JD for Phillips66: Candidates for regular U.S. positions must be a U.S. citizen or national, or an alien admitted as permanent resident, refugee, asylee or temporary resident under 8 U.S.C. 1160(a)(1). Individuals with temporary visas such as E, F-1, H-1, H-2, L, B, J, or TN or who need sponsorship for work authorization now or in the future, are not eligible for hire.

**Comment by vanshb03** [comment]
Hey @xiangddang .

Updated on the repo. Thank you for your contribution!
