### ISSUE TITLE
SIG Quantitative Trader Intern

### ISSUE THREAD

**Issue by Agnimandur** [Ouckah/Summer2025-Internships#72]
### Link to Internship Posting

https://careers.sig.com/job/8326/Quantitative-Trader-Internship-Summer-2025

### Company Name

SIG

### Internship Title

Quantitative Trader Intern

### Location

Bala Cynwyd, PA | New York City, NY | Chicago, IL

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

soswal@andrew.cmu.edu

### Extra Notes (Optional)

This is the SIG quant trading internship for undergrads (class of 2026).

**Comment by Ouckah** [comment]
Hi @Agnimandur! Unfortunately this position has already been added. However, I saw there are new locations with this position. Would you be able to make a PR editing the locations (so you can show up as a contributor)? Sorry, we don't currently have an "edit" option with the postings, but we're adding it soon!

**Comment by Ouckah** [comment]
Wait I'm a liar this is qt...

**Comment by Ouckah** [comment]
Sorry about the confusion LMAO, good find!

**Comment by Ouckah** [comment]
I'll fix that once I get access to my laptop
