### ISSUE TITLE
Issue: Broken Cisco Internship Link

### ISSUE THREAD

**Issue by nicolasgarza** [Ouckah/Summer2025-Internships#728]
### Select a category

Suggestion

### Issue/Question/Closed Internship

New link:
https://jobs.cisco.com/jobs/ProjectDetail/Software-Engineer-I-Intern-United-States/1427387

Old link (Broken):
https://jobs.cisco.com/jobs/ProjectDetail/Software-Engineer-I-Intern-United-States/1427387?user=1

**Comment by amyipdev** [comment]
Second this

**Comment by vanshb03** [comment]
Hey @nicolasgarza @amyipdev ,

Updated link in the most recent commit. Thank you for your contributions!
