### ISSUE TITLE
Issue: Goldman Link is Broken

### ISSUE THREAD

**Issue by amyipdev** [Ouckah/Summer2025-Internships#745]
### Select a category

Other

### Issue/Question/Closed Internship

![image](https://github.com/user-attachments/assets/669c4521-f81e-4685-b627-273c48c4b075)

**Comment by vanshb03** [comment]
Hey @amyipdev ,

Just tested it on my end and it appears to be working. Will add the link here for reference: [bit.ly/4dLtR8F](https://bit.ly/4dLtR8F)
