### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by aceeedev** [Ouckah/Summer2025-Internships#778]
### Link to Internship Posting

https://jobs.careers.microsoft.com/global/en/share/1755483

### Company Name

Microsoft

### Internship Title

Software Engineer: Fullstack Intern Opportunities for University Students, Mountain View

### Location

Mountain View, CA

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

cyberandrew03@gmail.com

**Comment by vanshb03** [comment]
Hey @aceeedev .

We already have the role on the repo. Thank you for your contribution!
