### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by yaylymov** [Ouckah/Summer2025-Internships#79]
### Link to Internship Posting

https://www.goldmansachs.com/careers/students/programs/americas/2025-summer-analyst-program.html

### Company Name

Goldman Sachs

### Internship Title

Summer Analyst Internship

### Location

Albany | Atlanta | Boston | Chicago | Dallas | Detroit | Hosuton | Los Angelos | Melbourne | Miami | Morristown | New York | Newport Beach | Norwalk | Perth | Philadelphia | Pittsburgh | Salt Lake City | San Francisco | Seattle | Sydney | Washington DC | West Palm Beach | Wilmington

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

berdiguly@yaylymov.com

**Comment by JhaoZ** [comment]
I'm not sure if this is the Tech one? It seems to be more investment focused

**Comment by yaylymov** [comment]
Yeah, this is more of financial internship. I will close this
