### ISSUE TITLE
Issue: Amadeus Internship Not Found

### ISSUE THREAD

**Issue by erinma6** [Ouckah/Summer2025-Internships#799]
### Select a category

Question

### Issue/Question/Closed Internship

I assume Amadeus closed their position listing because it can't be found when clicking the link.

**Comment by DereC4** [comment]
can verify 

![image](https://github.com/user-attachments/assets/957836cb-2067-4728-9b83-74359aa56d70)

**Comment by vanshb03** [comment]
Hey @DereC4 @erinma6 ,

Closed the internship in the most recent commit. Thank you for your contributions!
