### ISSUE TITLE
New Internship - Robinhood

### ISSUE THREAD

**Issue by nicolasgarza** [Ouckah/Summer2025-Internships#804]
### Link to Internship Posting

https://app.ripplematch.com/v2/public/company/robinhood

### Company Name

Robinhood

### Internship Title

Multiple Roles

### Location

Menlo Park, CA | New York, NY

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

nicolas.garza@gmail.com

**Comment by vanshb03** [comment]
Hey @nicolasgarza ,

Feel free to create issues for every role.

Thank you for your contribution!
