### ISSUE TITLE
Robinhood Software Engineering Intern, iOS (2025)

### ISSUE THREAD

**Issue by dchen024** [Ouckah/Summer2025-Internships#817]
### Link to Internship Posting

https://app.ripplematch.com/v2/public/job/61af82f4

### Company Name

Robinhood

### Internship Title

Software Engineering Intern, iOS (2025)

### Location

Menlo Park, CA, USA | New York, NY, USA

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

danielchen297@gmail.com

**Comment by vanshb03** [comment]
Hey @dchen024 ,

This role is already on the repo. Thank you for your contribution!
