### ISSUE TITLE
Issue: Internship Closed 

### ISSUE THREAD

**Issue by candiceKD** [Ouckah/Summer2025-Internships#823]
### Select a category

Closed Internship

### Issue/Question/Closed Internship

These Positions closed : 
Amadeus | Software Engineer Intern | Irving, TX | Aug 21
Plexus | Product Engineer Intern | Buffalo Grove, IL | Aug 20
Plexus | Design Assurance Engineer Intern | locations Neenah, WI | Aug 20

**Comment by vanshb03** [comment]
Hey @candiceKD ,

Closed the internships! Thank you for your contribution!
