### ISSUE TITLE
Issue: Unsponsored internship

### ISSUE THREAD

**Issue by NotJerwee** [Ouckah/Summer2025-Internships#881]
### Select a category

Other

### Issue/Question/Closed Internship

Truist DOES NOT sponsor applicants for employment for their "2025 Technology and Innovation Internship" but the repo
doesn't have the emoji on it.

[https://careers.truist.com/us/en/job/R0092584](url)
<img width="801" alt="Screenshot 2024-08-27 at 10 11 35 AM" src="https://github.com/user-attachments/assets/bdce04f8-0cb4-497c-88b0-94a41358d11f">

**Comment by vanshb03** [comment]
Hey Nephew @NotJerwee ,

Updated Sponsorship state. Thank you for your contribution!
