### ISSUE TITLE
Issue: Closed internship for Phillips Software Engineer Internship

### ISSUE THREAD

**Issue by NotJerwee** [Ouckah/Summer2025-Internships#882]
### Select a category

Closed Internship

### Issue/Question/Closed Internship

Title

https://www.careers.philips.com/student/global/en/job/534202/Intern-Software-Engineer-Plymouth-MN-Summer-2025

**Comment by vanshb03** [comment]
Hey @NotJerwee  ,

Thank you for your contribution. The role is closed :)
