### ISSUE TITLE
Issue: Replace the TD Bank's internship application in English instead of French.

### ISSUE THREAD

**Issue by NotJerwee** [Ouckah/Summer2025-Internships#992]
### Select a category

Suggestion

### Issue/Question/Closed Internship

As the title stated, TD Bank's "apply" directs me to this page which is in French: https://td.wd3.myworkdayjobs.com/fr-CA/TD_Bank_Careers/job/Mount-Laurel-New-Jersey/XMLNAME-2025-Summer-Internship-Program----Platforms---Technology---Software-Engineer_R_1365598

Though applicants can change the language back to English, it would be more convenient to arrive at the application in English once they click "Apply": https://td.wd3.myworkdayjobs.com/en-US/TD_Bank_Careers/job/Mount-Laurel-New-Jersey/XMLNAME-2025-Summer-Internship-Program----Platforms---Technology---Software-Engineer_R_1365598

**Comment by vanshb03** [comment]
Hey @NotJerwee ,

Made the change. Thank you for your contribution!
