### ISSUE TITLE
Issue: Textron requires US Citizens

### ISSUE THREAD

**Issue by Yug3737** [Ouckah/Summer2025-Internships#995]
### Select a category

Suggestion

### Issue/Question/Closed Internship

Please mention the US citizen icon in front of Textron's SWE Internship.

**Comment by vanshb03** [comment]
Hey @Yug3737 ,

It already has the US Flag on the role. Thank you for your contribution.

**Comment by Yug3737** [comment]
Thanks. My bad, the color matched the background hence I didn't notice.

Yug

**Comment by vanshb03** [comment]
Definitely brings to light an issue, feel free to share another emoji that is both Desktop and Mobile compatible :)
